[package]
name = "not actually using cargo to build yet, just deps"
version = "0.0.1"
authors = []
[lib]
name = "dummy"
path = "dummy.rs"
[dependencies.regex]
regex = "0.1.9"
[dependencies.regex_macros]
regex_macros = "0.1.4"
#[dependencies.bindgen]
#git = "https://github.com/crabtw/rust-bindgen.git"
[dependencies.autollvm]
path = "../autollvm"

