[package]
name = "not actually using cargo to build yet, just deps"
version = "0.0.1"
authors = []
[lib]
name = "dummy"
path = "dummy.rs"
[dependencies]
#regex = "0.1.9"
#regex_macros = "0.1.4"
vec_map = "0.6"
#[dependencies.bindgen]
#git = "https://github.com/crabtw/rust-bindgen.git"
[dependencies.autollvm]
path = "../autollvm"

